# File: backend/db/migrations/versions/d89992459590_create_solved_jira_tickets_table_for_rag.py
"""Create solved jira tickets table for RAG

Revision ID: d89992459590
Revises: 9940803aa6aa
Create Date: 2025-09-19 13:52:43.844970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = 'd89992459590'
down_revision = '9940803aa6aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solved_jira_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_key', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solved_jira_tickets_id'), 'solved_jira_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_solved_jira_tickets_ticket_key'), 'solved_jira_tickets', ['ticket_key'], unique=True)
    
    # --- FIX: The following tables are obsolete and were correctly removed. ---
    op.drop_table('actions_log')
    op.drop_table('jira_tickets')
    
    # --- FLAWLESS FIX ---
    # The incorrect alterations to the 'validations_log' table have been REMOVED from this migration.
    # This migration was incorrectly changing the 'confidence' column to a String, dropping 'validated_at',
    # and making 'status' nullable, which caused a mismatch with the SQLAlchemy model.
    # The schema is now managed correctly by the other migration files.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ticket_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='jira_tickets_pkey')
    )
    op.create_index('ix_jira_tickets_ticket_key', 'jira_tickets', ['ticket_key'], unique=True)
    op.create_index('ix_jira_tickets_id', 'jira_tickets', ['id'], unique=False)
    op.create_table('actions_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ticket_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='actions_log_pkey')
    )
    op.create_index('ix_actions_log_ticket_key', 'actions_log', ['ticket_key'], unique=False)
    op.create_index('ix_actions_log_id', 'actions_log', ['id'], unique=False)
    op.drop_index(op.f('ix_solved_jira_tickets_ticket_key'), table_name='solved_jira_tickets')
    op.drop_index(op.f('ix_solved_jira_tickets_id'), table_name='solved_jira_tickets')
    op.drop_table('solved_jira_tickets')
    # ### end Alembic commands ###
