# File: backend/db/migrations/script.py.mako
"""Create resolution log table

Revision ID: e153e2875902
Revises: d89992459590
Create Date: 2025-09-19 14:39:51.323144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e153e2875902'
down_revision = 'd89992459590'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_key', sa.String(), nullable=False),
    sa.Column('solution_posted', sa.Text(), nullable=False),
    sa.Column('llm_provider_model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_log_id'), 'resolution_log', ['id'], unique=False)
    op.create_index(op.f('ix_resolution_log_ticket_key'), 'resolution_log', ['ticket_key'], unique=False)
    op.alter_column('solved_jira_tickets', 'resolution',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('validations_log', 'module',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('validations_log', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validations_log', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('validations_log', 'module',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('solved_jira_tickets', 'resolution',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_resolution_log_ticket_key'), table_name='resolution_log')
    op.drop_index(op.f('ix_resolution_log_id'), table_name='resolution_log')
    op.drop_table('resolution_log')
    # ### end Alembic commands ###
